services:
  db:
    env_file:
      - path: "docker/env/db"
        required: true
      - path: "docker/env/db.local"
        required: false
    shm_size: "${DB_SHM_SIZE:-8g}"
    image: "postgres:17.7-trixie"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ${PWD}/docker/data/db/:/data/:rw
      - ${PWD}/docker/conf/db/postgresql.dev.conf:/etc/postgresql/postgresql.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5

  main:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: "docker/env/main"
        required: true
      - path: "docker/env/main.local"
        required: false
    volumes:
      - .:/app
    depends_on:
      - db
